name: "Setup Kubeasy"
description: "Install the kubeasy CLI and set up a Kind cluster with infrastructure (Kyverno + local-path-provisioner) for Kubeasy challenges"

branding:
  icon: "terminal"
  color: "blue"

inputs:
  version:
    description: "Version of kubeasy CLI to install (e.g. v2.5.2). Defaults to latest."
    required: false
    default: "latest"
  api-key:
    description: "Kubeasy API key for authentication. Sets the KUBEASY_API_KEY environment variable."
    required: true

outputs:
  version:
    description: "Installed kubeasy CLI version"
    value: ${{ steps.install-cli.outputs.version }}

runs:
  using: "composite"
  steps:
    # ── Step 1: Install kubeasy CLI ───────────────────────────────────────
    - name: Install kubeasy CLI
      id: install-cli
      shell: bash
      env:
        KUBEASY_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Install kubeasy CLI"

        if [ "${KUBEASY_VERSION}" = "latest" ]; then
          echo "Installing latest version of kubeasy CLI..."
          # Unset KUBEASY_VERSION so install.sh resolves the latest version
          # itself via the /latest endpoint instead of using "latest" literally.
          curl -fsSL "https://download.kubeasy.dev/install.sh" \
            | env -u KUBEASY_VERSION KUBEASY_INSTALL_DIR=/usr/local/bin sh
        else
          echo "Installing kubeasy CLI ${KUBEASY_VERSION}..."
          curl -fsSL "https://download.kubeasy.dev/kubeasy-cli/${KUBEASY_VERSION}/install.sh" \
            | KUBEASY_VERSION="${KUBEASY_VERSION}" KUBEASY_INSTALL_DIR=/usr/local/bin sh
        fi

        # Capture version without a live pipe to avoid SIGPIPE with pipefail:
        # `head -1` on a live process would cause kubeasy to exit with 141,
        # triggering the `|| echo 'unknown'` fallback and producing a
        # multi-line value that fails the GITHUB_OUTPUT "Invalid format" check.
        RAW_VERSION="$(kubeasy version 2>/dev/null || kubeasy --version 2>/dev/null || echo 'unknown')"
        INSTALLED_VERSION="$(echo "$RAW_VERSION" | head -1)"
        echo "version=${INSTALLED_VERSION}" >> "$GITHUB_OUTPUT"
        echo "kubeasy CLI installed: ${INSTALLED_VERSION}"
        echo "::endgroup::"

    # ── Step 2: Set API key ───────────────────────────────────────────────
    - name: Set API key
      shell: bash
      run: echo "KUBEASY_API_KEY=${{ inputs.api-key }}" >> "$GITHUB_ENV"

    # ── Step 3: Setup cluster and infrastructure ──────────────────────────
    - name: Setup Kubeasy environment
      shell: bash
      env:
        KUBEASY_API_KEY: ${{ inputs.api-key }}
      run: |
        echo "::group::Setup Kubeasy environment"
        kubeasy setup
        echo "::endgroup::"
